### ISSUE TITLE
Please develop the 1.16.5 version

### ISSUE THREAD

**Issue by LeePC** [Yancey2023/CommandFallingBlock#2]
I hope there's 1.16.5 version, too
希望有1.16.5版本

**Comment by Yancey2023** [comment]
我试试

**Comment by LeePC** [comment]
[It's a video made with your mods](https://www.youtube.com/watch?v=gIE_8A5GKis)

**Comment by Yancey2023** [comment]
the 1.1.6.5 version is released just now, but i am lazy to test it fully, hhhh. If it has any bugs, it is welcome to give me an issue. Hoping that you can make wonderful videos.

**Comment by LeePC** [comment]
Thank you for creating a plugin

**Comment by LeePC** [comment]
Failed to start Minecraft:
java.lang.RuntimeException: Error creating Mixin config commandfallingblock.mixins.json for mod commandfallingblock
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config commandfallingblock.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 11 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.6 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 14 more
Exiting with -1

fix please

**Comment by Yancey2023** [comment]
please use JAVA17, rather than JAVA 8, i hope it helps

**Comment by LeePC** [comment]
1.16.5 java 17 no support....

**Comment by Yancey2023** [comment]
my mistake... i will solve it soon

**Comment by Yancey2023** [comment]
JAVA 17 support 1.1.6.5
![{8C1B5331-2424-4cbf-9A72-51E35FCBF9A1}](https://github.com/Yancey2023/CommandFallingBlock/assets/135342560/c312eddb-e973-4041-afda-ca6cea35b4f7)

**Comment by Yancey2023** [comment]
> 1.16.5 java 17 no support....

Beside, i have update my mod , which support Java 8 now. You can download it in the lastest release.
